
controller:

  JCasC:
    enabled: true

    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
            - credentials:
              - usernamePassword:
                  description: "Dockerhub Account"
                  id: "dockerhub-owllark"
                  password: ${dockerhub-password}
                  scope: GLOBAL
                  username: "owllark"
              - basicSSHUserPrivateKey:
                  description: "Owllark github credentials"
                  id: "github-owllark"
                  privateKeySource:
                    directEntry:
                      privateKey: ${github-ssh}
                  scope: GLOBAL
                  username: "Owllark"
              - string:
                  id: "GITHUB_HOST_KEY"
                  scope: GLOBAL
                  secret: ${github-host-key}
              - string:
                  id: "github-token"
                  scope: GLOBAL
                  secret: ${github-token}
              - string:
                  id: "argocd-webhook-token"
                  scope: GLOBAL
                  secret: ${argocd-webhook-token}

