controller:
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
    ingressClassName: "nginx"
    tls:
      - hosts:
          - <{jenkins.hostname}>
        secretName: jenkins-certificate-tls
    hostName: <{jenkins.hostname}>
    rules:
      - http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: jenkins
                  port:
                    number: 8080
