imageTag: "7.16.2"

replicas: 1

resources:
  requests:
    memory: "500Mi"
    cpu: "0.5"
  limits:
    memory: "1Gi"
    cpu: "1" 

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5

clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"