imageTag: "7.16.2"

replicas: 1

resources:
  requests:
    memory: "500Mi"
    cpu: "0.5"
  limits:
    memory: "1Gi"
    cpu: "1" 

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
  
kibanaConfig:
  elasticsearchHosts: "http://elasticsearch-master:9200"

ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
  ingressClassName: "nginx"
  tls:
    - hosts:
      - <{elk.hostname}>
      secretName: elk-certificate-tls
  hosts:
    - <{elk.hostname}>
  path: /
  pathtype: "Prefix"

