persistence:
  enabled: true

resources:
  requests:
    cpu: "0.1"
    memory: "400Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 3

elasticsearch:
  password: password
  username: username

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline: 
 logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      if "Application Log" in [message] {
        elasticsearch {
          hosts => "https://elasticsearch-master:9200"
          ssl_certificate_verification => false
          user => "{{ .Values.elasticsearch.username | default "" }}"
          password => "{{ .Values.elasticsearch.password | default "" }}"
          index => "my_index"
        }
      } else {
        elasticsearch {
          hosts => "https://elasticsearch-master:9200"
          ssl_certificate_verification => false
          user => "{{ .Values.elasticsearch.username | default "" }}"
          password => "{{ .Values.elasticsearch.password | default "" }}"
        }
      }
    }

service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080