apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-staging
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.jenkins: 'webhook:jenkins'
spec:
  destination:
    name: ''
    namespace: staging
    server: 'https://kubernetes.default.svc'
  source:
    path: ./deploy/dev
    repoURL: <{repoUrlSSH}>
    targetRevision: staging
    directory:
      recurse: true
      exclude: prod_only_manifests/*
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
