apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    name: ''
    namespace: production
    server: 'https://kubernetes.default.svc'
  source:
    path: ./deploy/dev
    repoURL: 'git@github.com:Owllark/igorbaran_devops_internship_practice.git'
    targetRevision: release
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
