apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-staging
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.jenkins: webhook:jenkins
spec:
  destination:
    name: ''
    namespace: staging
    server: 'https://kubernetes.default.svc'
  source:
    path: ./deploy/dev
    repoURL: 'git@github.com:Owllark/igorbaran_devops_internship_practice.git'
    targetRevision: development
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
   automated:
    selfHeal: true
    prune: true