apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.jenkins: |
    url: https://jenkins.owllark.mooo.com/generic-webhook-trigger/invoke?token=test
    headers:
      - name: Content-Type
        value: application/json
    subscriptions:
      - recipients:
          - jenkins
        triggers:
          - on-deployed
  template.app-deployed: |
    webhook:
      jenkins:
        method: POST
  trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.operationState.syncResult.revision
        send:
        - app-deployed
        when: app.status.operationState.phase in ['Succeeded']
     