server:
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    labels: {}
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx
    tls:
      - hosts:
        - <{argocd.hostname}>
        secretName: argocd-certificate-tls
    hostname: <{argocd.hostname}>
    path: /
    pathtype: "Prefix"

controller:

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi