## Custom resource configuration
#sscrds:
  # -- Install and upgrade CRDs
  #install: false
server:
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    labels: {}
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx
    tls:
      - hosts:
        - argocd.owllark.chickenkiller.com
        secretName: argocd-certificate-tls
    rules:
      - host: argocd.owllark.chickenkiller.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http