apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  containers:
  - name: backend-test
    image: owllark/jenkins-agent-backend-test:latest
    tty: true
  imagePullSecrets:
  - name: dockerhub-secret
  resources:
    limits:
      cpu: "500m"
      memory: "1024Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"