apiVersion: v1
kind: Pod
metadata:
  namespace: "jenkins"
spec:
  containers:
    - name: build
      image: owllark/jenkins-agent-build:latest
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: podman-volume
      resources:
        limits:
          cpu: "500m"
          memory: "2048Mi"
        requests:
          cpu: "250m"
          memory: "256Mi"
  imagePullSecrets:
  - name: dockerhub-secret
  restartPolicy: Never
  volumes:
    - name: podman-volume
      emptyDir: {}
